#!/usr/bin/with-contenv bash

if [ ! -d /share/nzbget/downloads ]; then
  echo "Creating /share/nzbget/downloads"
  mkdir -p /share/nzbget/downloads
fi

if [ ! -d /data/config ]; then
  echo "Creating /data/config"
  mkdir -p /data/config
fi
