#!/usr/bin/with-contenv bash

if [ ! -d /share/nzbget]; then
  echo "Creating /share/nzbget"
  mkdir -p /share/nzbget
fi

if [ ! -d /data/config ]; then
  echo "Creating /data/config"
  mkdir -p /data/config
fi
