dist: xenial
os: linux
language: ruby
addons:
  apt:
    packages:
      - jq
      - docker-ce
services:
  - docker
before_install:
  - sudo docker run --privileged linuxkit/binfmt:v0.7
  - sudo docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf --oci-worker-platform linux/arm64 --oci-worker-platform linux/386
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234
branches:
  only:
    - master
    - develop
jobs:
  include:
#START_GEN_BUILD
    - stage: build
      env:
        - ADDON="influxdb2" ARCH="amd64" CONFIG="config.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ARCHS=$ARCH ./scripts/travis-build.sh $ADDON
    - stage: build
      env:
        - ADDON="influxdb2" ARCH="armv7" CONFIG="config.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ARCHS=$ARCH ./scripts/travis-build.sh $ADDON
    - stage: build
      env:
        - ADDON="lego" ARCH="armv7" CONFIG="config.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ARCHS=$ARCH ./scripts/travis-build.sh $ADDON
#END_GEN_BUILD
#START_GEN_DONE
    - stage: manifest
      env:
        - ADDON="influxdb2" ARCHS="amd64 armv7" CONFIG="config.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ./scripts/travis-set-manifest.sh $ADDON
    - stage: manifest
      env:
        - ADDON="lego" ARCHS="armv7" CONFIG="config.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ./scripts/travis-set-manifest.sh $ADDON
#END_GEN_DONE
