dist: xenial
os: linux
language: ruby
addons:
  apt:
    packages:
      - jq
      - docker-ce
services:
  - docker
before_install:
  - sudo docker run --privileged linuxkit/binfmt:v0.7
  - sudo docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf --oci-worker-platform linux/arm64 --oci-worker-platform linux/386
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234
jobs:
  include:
#START_GEN_BUILD
    - stage: build
      env:
        - ADDON="golang" ARCH="aarch64" CONFIG="config.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ARCHS=$ARCH ./travis-build.sh $ADDON
    - stage: build
      env:
        - ADDON="golang" ARCH="amd64" CONFIG="config.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ARCHS=$ARCH ./travis-build.sh $ADDON
    - stage: build
      env:
        - ADDON="golang" ARCH="armhf" CONFIG="config.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ARCHS=$ARCH ./travis-build.sh $ADDON
    - stage: build
      env:
        - ADDON="golang" ARCH="armv7" CONFIG="config.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ARCHS=$ARCH ./travis-build.sh $ADDON
    - stage: build
      env:
        - ADDON="golang" ARCH="i386" CONFIG="config.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ARCHS=$ARCH ./travis-build.sh $ADDON
    - stage: build
      env:
        - ADDON="hello-world" ARCH="aarch64" CONFIG="config-test.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ARCHS=$ARCH ./travis-build.sh $ADDON
    - stage: build
      env:
        - ADDON="hello-world" ARCH="amd64" CONFIG="config-test.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ARCHS=$ARCH ./travis-build.sh $ADDON
    - stage: build
      env:
        - ADDON="hello-world" ARCH="armhf" CONFIG="config-test.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ARCHS=$ARCH ./travis-build.sh $ADDON
    - stage: build
      env:
        - ADDON="hello-world" ARCH="armv7" CONFIG="config-test.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ARCHS=$ARCH ./travis-build.sh $ADDON
    - stage: build
      env:
        - ADDON="hello-world" ARCH="i386" CONFIG="config-test.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ARCHS=$ARCH ./travis-build.sh $ADDON
    - stage: build
      env:
        - ADDON="lego" ARCH="armv7" CONFIG="config.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ARCHS=$ARCH ./travis-build.sh $ADDON
#END_GEN_BUILD
#START_GEN_DONE
    - stage: manifest
      env:
        - ADDON="golang" ARCHS="aarch64 amd64 armhf armv7 i386" CONFIG="config.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ./travis-set-manifest.sh $ADDON
    - stage: manifest
      env:
        - ADDON="hello-world" ARCHS="aarch64 amd64 armhf armv7 i386" CONFIG="config-test.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ./travis-set-manifest.sh $ADDON
    - stage: manifest
      env:
        - ADDON="lego" ARCHS="armv7" CONFIG="config.json" 
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - ./travis-set-manifest.sh $ADDON
#END_GEN_DONE
