language: ruby
sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
env:
  - ADDON="caddy"
script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - scripts/build.sh $ADDON
