sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq sed
env:
  - ADDON="find3" ARCHS="--armhf"
script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - build.sh $ADDON
