sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
env:
  - ADDON="hello_world" ARCHS="--armv7 --armhf --amd64 --aarch64 --i386" BUILD="true"
script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - ./build.sh $ADDON
