sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
env:
  - ADDON="find3"
  - BUILD="true"
script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - ./build.sh $ADDON
